version: '3.3'

services:

  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"      
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data

  