version: '3.3'

services:

  pgsql:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"      
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
      - ./docker-data/pg-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    command: redis-server 
    ports:
    - "6379:6379"
    volumes:
    - ./docker-data/redis-data:/var/lib/redis
    - ./configs/docker/redis.conf:/usr/local/etc/redis/redis.conf
    

 

    
