#Config file for user-service

#Postgresql
db:
  user: test
  password: test
  port: 5432
  host: localhost
  dbname: test

redis:
  host: localhost
  port: 6379
  db: 0
  password: test

server:
  salt: testsalt
  jwtkey: testkey
  tokenLifeTime: 300 #sec
  
